Traceback (most recent call last):
  File "main.py", line 37, in <module>
    main()
  File "main.py", line 34, in main
    run_classifier(folder_path, optimizer_string, workers, device)
  File "/home/ppo208/lab2/classifier.py", line 15, in run_classifier
    optimizer = get_optimizer(optimizer_string, neural_net)
  File "/home/ppo208/lab2/classifier.py", line 103, in get_optimizer
    return optim.Adam(neural_net.parameters(), lr=0.01, momentum=0.9)
TypeError: __init__() got an unexpected keyword argument 'momentum'
